# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

inhibit_all_warnings!

target 'ParkHere' do

pod "AFNetworking", "~> 2.0"
pod 'EstimoteSDK'

end

target 'ParkHereTests' do

end

